// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice.Data.Context;

#nullable disable

namespace Practice.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115163823_IntershipAssignment")]
    partial class IntershipAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Practice.Data.Entities.AssignmentStatus", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("status_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("status_id");

                    b.ToTable("AssignmentStatuses");
                });

            modelBuilder.Entity("Practice.Data.Entities.Department", b =>
                {
                    b.Property<int>("department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("department_id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Practice.Data.Entities.IntershipAssignment", b =>
                {
                    b.Property<int>("assignment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("final_grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("individual_task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("status_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("student_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("supervisor_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("topic_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("assignment_id");

                    b.HasIndex("status_id");

                    b.HasIndex("student_id");

                    b.HasIndex("supervisor_id");

                    b.HasIndex("topic_id");

                    b.ToTable("IntershipAssignments");
                });

            modelBuilder.Entity("Practice.Data.Entities.IntershipTopic", b =>
                {
                    b.Property<int>("topic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_available")
                        .HasColumnType("INTEGER");

                    b.Property<int>("organization_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("topic_id");

                    b.HasIndex("organization_id");

                    b.ToTable("IntershipTopics");
                });

            modelBuilder.Entity("Practice.Data.Entities.Organization", b =>
                {
                    b.Property<int>("organization_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("organization_id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Practice.Data.Entities.Position", b =>
                {
                    b.Property<int>("position_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("position_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("position_id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Practice.Data.Entities.ReportStatus", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("status_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("status_id");

                    b.ToTable("ReportStatuses");
                });

            modelBuilder.Entity("Practice.Data.Entities.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Practice.Data.Entities.Specialty", b =>
                {
                    b.Property<int>("specialty_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("specialty_id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("Practice.Data.Entities.Student", b =>
                {
                    b.Property<int>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("group_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("record_book_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("student_id");

                    b.HasIndex("group_id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Practice.Data.Entities.StudentGroup", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("entry_year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("group_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("specialty_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("group_id");

                    b.HasIndex("specialty_id");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("Practice.Data.Entities.Supervisor", b =>
                {
                    b.Property<int>("supervisor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("department_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("position_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("supervisor_id");

                    b.HasIndex("department_id");

                    b.HasIndex("position_id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("Practice.Data.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("role_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Practice.Data.Entities.IntershipAssignment", b =>
                {
                    b.HasOne("Practice.Data.Entities.AssignmentStatus", "AssignmentStatus")
                        .WithMany()
                        .HasForeignKey("status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Entities.Student", "Student")
                        .WithMany("IntershipAssignments")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Entities.Supervisor", "Supervisor")
                        .WithMany("IntershipAssignments")
                        .HasForeignKey("supervisor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Entities.IntershipTopic", "IntershipTopic")
                        .WithMany()
                        .HasForeignKey("topic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignmentStatus");

                    b.Navigation("IntershipTopic");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Practice.Data.Entities.IntershipTopic", b =>
                {
                    b.HasOne("Practice.Data.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("organization_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Practice.Data.Entities.Student", b =>
                {
                    b.HasOne("Practice.Data.Entities.StudentGroup", "StudentGroup")
                        .WithMany("Students")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Practice.Data.Entities.Student", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Practice.Data.Entities.StudentGroup", b =>
                {
                    b.HasOne("Practice.Data.Entities.Specialty", "Specialty")
                        .WithMany("StudentGroups")
                        .HasForeignKey("specialty_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Practice.Data.Entities.Supervisor", b =>
                {
                    b.HasOne("Practice.Data.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Entities.User", "User")
                        .WithOne("Supervisor")
                        .HasForeignKey("Practice.Data.Entities.Supervisor", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Practice.Data.Entities.User", b =>
                {
                    b.HasOne("Practice.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Practice.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Practice.Data.Entities.Specialty", b =>
                {
                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("Practice.Data.Entities.Student", b =>
                {
                    b.Navigation("IntershipAssignments");
                });

            modelBuilder.Entity("Practice.Data.Entities.StudentGroup", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Practice.Data.Entities.Supervisor", b =>
                {
                    b.Navigation("IntershipAssignments");
                });

            modelBuilder.Entity("Practice.Data.Entities.User", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("Supervisor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
